### ISSUE TITLE
yarn throws error while `make deps` 

### ISSUE THREAD

**Issue by rnsrk** [FAU-CDI/drincw#1]
Hi, during the installation at step `$ make deps` the subcommand "yarn install" leads to "ERROR: [Errno 2] No such file or directory: 'install'" on ubuntu 22.04 with yarn 0.32+git. You may use `npm i` instead?

**Comment by tkw1536** [comment]
You're using the wrong yarn. `0.32+git` is [scenario testing of Unix command line tools](https://manpages.ubuntu.com/manpages/xenial/man1/yarn.1.html).
As the README says, you need to install yarn from https://yarnpkg.com/.
